import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🔧 Documentation Technique',
      items: [
        { type: 'autogenerated', dirName: 'technicals' }, // automatique
      ],
    },
    {
      type: 'category',
      label: '👤 Documentation Utilisateur',
      items: [
        { type: 'autogenerated', dirName: 'users' }, // automatique
      ],
    },
    {
      type: 'category',
      label: '🎓 Tutoriels',
      items: [
        { type: 'autogenerated', dirName: 'tutorial-basics' }, // auto aussi
      ],
    },
  ],
};

export default sidebars;
