import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🔧 Documentation Technique',
      items: [
        'technicals/intro',
        'technicals/requirements',
        {
          type: 'category',
          label: 'Classes',
          items: [
            'technicals/principale_class',
            {
              type: 'category',
              label: 'Menus',
              items: [
                { type: 'autogenerated', dirName: 'technicals/menu' }, // automatique
              ],            
            }
          ],
        }
      ],
    },
    {
      type: 'category',
      label: '👤 Documentation Utilisateur',
      items: [
        { type: 'autogenerated', dirName: 'users' }, // automatique
      ],
    },
  ],
};

export default sidebars;
