import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🔧 Documentation Technique',
      items: [
        'technicals/intro',
        'technicals/requirements',
        'technicals/maintenance',
        {
          type: 'category',
          label: 'Classes',
          items: [
            { type: 'autogenerated', dirName: 'technicals/classes' }, // automatique
          ],
        }
      ],
    },
    {
      type: 'category',
      label: '👤 Documentation Utilisateur',
      items: [
        { type: 'autogenerated', dirName: 'users' }, // automatique
      ],
    },
  ],
};

export default sidebars;
